type Coverage = { moduleId: string; label: string; category: string; status: "completed" | "no-findings" | "failed"; findingCount: number; notices: string[]; error?: string };
type Finding = { category: string; title: string; severity: string; summary: string; sourceUrl?: string; evidenceQuality?: "direct" | "corroborated" | "context" | "lead"; leadStatus?: "verified" | "review" | "unverified"; collectedAt?: string; sourceCount?: number; limitations?: string[]; data?: Record<string, unknown> };
type ReconResult = { target?: { normalized?: string; type?: string }; findings?: Finding[]; risk?: { score: number; level: string }; summary?: string; coverage?: Coverage[]; persistence?: { status: "saved" | "degraded"; warning?: string }; completedAt?: string };

const escapeHtml = (value: string) => value.replace(/[&<>'"]/g, char => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#039;", '"': "&quot;" }[char] || char));
const evidenceLine = (item: Finding) => `- **Evidence quality:** ${item.evidenceQuality || "context"}\n- **Review status:** ${item.leadStatus || "verified"}\n- **Declared sources:** ${item.sourceCount || (item.sourceUrl ? 1 : 0)}\n${item.collectedAt ? `- **Collected:** ${item.collectedAt}\n` : ""}${item.limitations?.length ? `- **Limitations:** ${item.limitations.join(" ")}\n` : ""}`;

export function markdownReport(result: ReconResult) {
  const findings = result.findings || [];
  const coverage = result.coverage || [];
  const coverageSection = coverage.length ? `## Source coverage and limitations\n\n${coverage.map(item => `- **${item.label}** (${item.category}): ${item.status}${item.findingCount ? `; ${item.findingCount} evidence record(s)` : ""}${item.error ? `; unavailable: ${item.error}` : ""}${item.notices.length ? `; note: ${item.notices.join(" ")}` : ""}`).join("\n")}\n\n${result.persistence?.status === "degraded" ? `> **Persistence warning:** ${result.persistence.warning || "This live result could not be fully stored in history."}\n\n` : ""}` : "## Source coverage and limitations\n\nNo module-coverage ledger was available for this run.\n\n";
  const ledger = findings.length ? `## Evidence quality ledger\n\n${["direct", "corroborated", "context", "lead"].map(kind => `- **${kind}:** ${findings.filter(item => (item.evidenceQuality || "context") === kind).length}`).join("\n")}\n\n` : "";
  return `# ReconGPT Intelligence Report\n\n**Target:** ${result.target?.normalized || "Unknown"}  \n**Target type:** ${result.target?.type || "Unknown"}  \n**Evidence score:** ${result.risk?.score ?? 0}/100 (${result.risk?.level || "low"})  \n**Completed:** ${result.completedAt || new Date().toISOString()}\n\n## Executive assessment\n\n${result.summary || "No summary is available."}\n\n## Verified passive findings\n\n${findings.map((item, index) => `### ${index + 1}. ${item.title}\n\n- **Category:** ${item.category}\n- **Severity:** ${item.severity}\n${evidenceLine(item)}- **Summary:** ${item.summary}\n${item.sourceUrl ? `- **Source:** ${item.sourceUrl}\n` : ""}`).join("\n")}${ledger}${coverageSection}## Methodology and limitations\n\nThis report aggregates passive public-information sources and provider data. It does not confirm ownership, intent, or exploitation risk, and it should be independently reviewed before action.\n`;
}

export function downloadReport(filename: string, mime: string, content: string) {
  const url = URL.createObjectURL(new Blob([content], { type: mime })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = filename; anchor.click(); URL.revokeObjectURL(url);
}

export function printableHtmlReport(result: ReconResult) {
  const findings = result.findings || [];
  const coverage = result.coverage || [];
  const coverageHtml = coverage.length ? `<h2>Source coverage and limitations</h2><ul>${coverage.map(item => `<li><strong>${escapeHtml(item.label)}</strong> (${escapeHtml(item.category)}): ${escapeHtml(item.status)}${item.findingCount ? `; ${item.findingCount} evidence record(s)` : ""}${item.error ? `; unavailable: ${escapeHtml(item.error)}` : ""}${item.notices.length ? `; note: ${escapeHtml(item.notices.join(" "))}` : ""}</li>`).join("")}</ul>${result.persistence?.status === "degraded" ? `<p class="warning"><strong>Persistence warning:</strong> ${escapeHtml(result.persistence.warning || "This live result could not be fully stored in history.")}</p>` : ""}` : "<h2>Source coverage and limitations</h2><p>No module-coverage ledger was available for this run.</p>";
  const findingHtml = findings.map(item => `<article><span class="tag">${escapeHtml(item.category)} · ${escapeHtml(item.severity)} · ${escapeHtml(item.evidenceQuality || "context")} · ${escapeHtml(item.leadStatus || "verified")}</span><h3>${escapeHtml(item.title)}</h3><p>${escapeHtml(item.summary)}</p><p class="meta">Declared sources: ${item.sourceCount || (item.sourceUrl ? 1 : 0)}${item.collectedAt ? ` · Collected: ${escapeHtml(item.collectedAt)}` : ""}</p>${item.limitations?.length ? `<p class="limitation"><strong>Limitations:</strong> ${escapeHtml(item.limitations.join(" "))}</p>` : ""}${item.sourceUrl ? `<a href="${escapeHtml(item.sourceUrl)}">Source evidence</a>` : ""}</article>`).join("");
  return `<!doctype html><html><head><meta charset="utf-8"><title>ReconGPT Report</title><style>body{font:14px/1.55 Inter,Arial,sans-serif;color:#17212b;max-width:960px;margin:42px auto;padding:0 30px}h1{font-size:30px;margin-bottom:0}.meta{color:#526170}.score{display:inline-block;background:#e8f8f3;color:#087358;padding:5px 10px;border-radius:99px;font-weight:700}article{border-top:1px solid #d9e0e7;padding:18px 0}h3{margin:0 0 6px}.tag{font-size:11px;text-transform:uppercase;letter-spacing:.08em;color:#526170}a{color:#087358}.warning{border-left:3px solid #ba7117;background:#fff8e8;padding:9px 12px}.limitation{color:#5c6871}@media print{body{margin:0;max-width:none}}</style></head><body><h1>ReconGPT Intelligence Report</h1><p class="meta">Target: <strong>${escapeHtml(result.target?.normalized || "Unknown")}</strong> · Type: ${escapeHtml(result.target?.type || "Unknown")} · Completed: ${escapeHtml(result.completedAt || new Date().toISOString())}</p><p class="score">Evidence score: ${result.risk?.score ?? 0}/100 · ${escapeHtml(result.risk?.level || "low")}</p><h2>Executive assessment</h2><p>${escapeHtml(result.summary || "No summary is available.")}</p><h2>Verified passive findings</h2>${findingHtml}${coverageHtml}<h2>Methodology and limitations</h2><p>This report aggregates passive public-information sources and provider data. It does not confirm ownership, intent, or exploitation risk, and it should be independently reviewed before action.</p></body></html>`;
}
