type ReconResult = { target?: { normalized?: string; type?: string }; findings?: Array<{ category: string; title: string; severity: string; summary: string; sourceUrl?: string; data?: Record<string, unknown> }>; risk?: { score: number; level: string }; summary?: string; completedAt?: string };

const escapeHtml = (value: string) => value.replace(/[&<>'"]/g, char => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#039;", '"': "&quot;" }[char] || char));
export function markdownReport(result: ReconResult) {
  const findings = result.findings || [];
  return `# ReconGPT Intelligence Report\n\n**Target:** ${result.target?.normalized || "Unknown"}  \n**Target type:** ${result.target?.type || "Unknown"}  \n**Evidence score:** ${result.risk?.score ?? 0}/100 (${result.risk?.level || "low"})  \n**Completed:** ${result.completedAt || new Date().toISOString()}\n\n## Executive assessment\n\n${result.summary || "No summary is available."}\n\n## Verified passive findings\n\n${findings.map((item, index) => `### ${index + 1}. ${item.title}\n\n- **Category:** ${item.category}\n- **Severity:** ${item.severity}\n- **Summary:** ${item.summary}\n${item.sourceUrl ? `- **Source:** ${item.sourceUrl}\n` : ""}\n`).join("\n")}\n## Methodology and limitations\n\nThis report aggregates passive public-information sources and provider data. It does not confirm ownership, intent, or exploitation risk, and it should be independently reviewed before action.\n`;
}
export function downloadReport(filename: string, mime: string, content: string) {
  const url = URL.createObjectURL(new Blob([content], { type: mime })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = filename; anchor.click(); URL.revokeObjectURL(url);
}
export function printableHtmlReport(result: ReconResult) {
  const findings = result.findings || [];
  return `<!doctype html><html><head><meta charset="utf-8"><title>ReconGPT Report</title><style>body{font:14px/1.55 Inter,Arial,sans-serif;color:#17212b;max-width:960px;margin:42px auto;padding:0 30px}h1{font-size:30px;margin-bottom:0}.meta{color:#526170}.score{display:inline-block;background:#e8f8f3;color:#087358;padding:5px 10px;border-radius:99px;font-weight:700}article{border-top:1px solid #d9e0e7;padding:18px 0}h3{margin:0 0 6px}.tag{font-size:11px;text-transform:uppercase;letter-spacing:.08em;color:#526170}a{color:#087358}@media print{body{margin:0;max-width:none}}</style></head><body><h1>ReconGPT Intelligence Report</h1><p class="meta">Target: <strong>${escapeHtml(result.target?.normalized || "Unknown")}</strong> · Type: ${escapeHtml(result.target?.type || "Unknown")} · Completed: ${escapeHtml(result.completedAt || new Date().toISOString())}</p><p class="score">Evidence score: ${result.risk?.score ?? 0}/100 · ${escapeHtml(result.risk?.level || "low")}</p><h2>Executive assessment</h2><p>${escapeHtml(result.summary || "No summary is available.")}</p><h2>Verified passive findings</h2>${findings.map(item => `<article><span class="tag">${escapeHtml(item.category)} · ${escapeHtml(item.severity)}</span><h3>${escapeHtml(item.title)}</h3><p>${escapeHtml(item.summary)}</p>${item.sourceUrl ? `<a href="${escapeHtml(item.sourceUrl)}">Source evidence</a>` : ""}</article>`).join("")}<h2>Methodology and limitations</h2><p>This report aggregates passive public-information sources and provider data. It does not confirm ownership, intent, or exploitation risk, and it should be independently reviewed before action.</p></body></html>`;
}
