export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  shodanApiKey: process.env.SHODAN_API_KEY ?? "",
  virustotalApiKey: process.env.VIRUSTOTAL_API_KEY ?? "",
  abuseIpdbApiKey: process.env.ABUSEIPDB_API_KEY ?? "",
  urlscanApiKey: process.env.URLSCAN_API_KEY ?? "",
  ipinfoToken: process.env.IPINFO_TOKEN ?? "",
  externalLlmApiKey: process.env.EXTERNAL_LLM_API_KEY ?? "",
} as const;
